name: scenekit_plugin
description: Flutter Plugin rendering 3d Scenes - 3d renderer development platform for iOS and Android mobile devices.
version: 0.0.12
repository: https://github.com/take2make/scenekit_plugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
  collection: ^1.16.0
  flutter_plugin_android_lifecycle: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.scenekit_plugin
        pluginClass: ScenekitPlugin
      ios:
        pluginClass: ScenekitPlugin