name: scenekit_plugin
description: Flutter Plugin for SceneKit - Apple's 3d renderer development platform for iOS mobile devices.
version: 0.0.2
repository: https://github.com/take2make/scenekit_plugin

environment:
  sdk: '>=2.18.0-95.0.dev <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ScenekitPlugin